version: '2'

services: 
  redis:
    image: "redis:alpine"
    ports:
     - "6379:6379"
  mongo:
    image: mongo
    restart: always
    ports:
     - "27017:27017"
  web:
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:
     - "3131:3131"
    depends_on:
      redis:
        condition: service_started
      mongo: 
        condition: service_started