export { default as addConfigFile } from './addConfigFile'
export { default as moveMissingSvgVersion } from './filesManagment'
export { default as isProduction } from './isProduction'
export { default as serializer } from './serializer'
export { default as svgToPng } from './svgToPng'
export { default as zipFolder } from './zipFolder'
export { default as getThemeDir } from './getThemeDir'
export * as redisTools from './redisTools'
export { getOutlined, getFilled, getSvgCode } from './getSvgCode'
export { default as getBase64 } from './getBase64'
export { default as getEncodedLink } from './updatingIcons/getEncodedLink'
export { default as isNewIcon } from './updatingIcons/isNewIcon'
export { default as prepareUpdatedIcon } from './updatingIcons/prepareTheUpdate'
