export { default as FontFactory } from './FontFactory'
export { default as SvgFactory } from './SvgFactory'
export { default as updateDBIcons } from './updateDBIcons'
export { default as updateCachedIcons } from './updateCachedIcons'
export { default as ImageFactory } from './imageFactory'
