name: Node.js CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  cache_node_modules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('package-lock.json') }}
        
      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm install

  Linting:
    needs: cache_node_modules
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2

      - name: Load node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('package-lock.json') }}

      - name: Install node_modules
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm install

      - name: Linting
        run: npm run lint
        
  Testing:
    needs: cache_node_modules
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2

      - name: Load node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('package-lock.json') }}

      - name: Install node_modules
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm install

      - name: Install required python packages
        run: sudo apt-get update && sudo apt-get install fontforge ttfautohint
      - name: Testing V1 APIs
        run: npm run test:v1
        
